[options]
; Configuration de base pour Odoo
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo_db
addons_path = /opt/odoo/server/addons, /opt/odoo/server/odoo/addons
data_dir = /opt/odoo/server/data
log_level = info
#logfile = /opt/odoo/server/odoo.log
xmlrpc_port = 8068
workers = 0
; Désactiver les limites de mémoire
limit_memory_hard = 0
limit_memory_soft = 0
limit_request = 0
limit_time_cpu = 0
limit_time_real = 0
max_cron_threads = 1
; Mode développement
dev_mode = True